[package]
name = "volume"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "volume"
path = "bin/main.rs"

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }

[target.'cfg(unix)'.build-dependencies]
pkg-config = "0.3"
cc = "1.0.70"
